import { Listing } from "./types";

// ============================================================================
// SAMPLE LISTING DATA
// ----------------------------------------------------------------------------
// ALL listings in this file are FICTIONAL SAMPLE DATA created to demonstrate
// the website's design and functionality. They are NOT real properties,
// are NOT currently for sale, and do NOT use real MLS® numbers.
// This file will eventually be replaced by a live CREA DDF feed — see
// lib/listings/sampleListingService.ts and lib/listings/listingService.ts.
// ============================================================================

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=1600&q=80`;

export const sampleListings: Listing[] = [
  {
    id: "hanover-starter-1",
    mlsNumber: "SAMPLE-100001",
    isSample: true,
    address: "214 10th Street",
    city: "Hanover",
    province: "ON",
    postalCode: "N4N 1R8",
    latitude: 44.1494,
    longitude: -81.0295,
    price: 449900,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Detached",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1350,
    lotSize: "50 x 110 ft",
    acreage: null,
    garage: "1 Car Attached",
    storeys: 1.5,
    yearBuilt: 1978,
    waterfront: false,
    headline: "Charming Starter Home in the Heart of Hanover",
    description:
      "A tidy, move-in-ready home on a quiet street close to schools and downtown Hanover. Great layout for a first-time buyer or young family, with a fenced backyard perfect for summer evenings.",
    featureGroups: [
      { title: "Interior", items: ["Updated kitchen", "Hardwood in living room", "Finished lower level"] },
      { title: "Exterior", items: ["Fenced backyard", "Attached garage", "Paved driveway"] },
    ],
    rooms: [
      { name: "Living Room", level: "Main", dimensions: "14x12" },
      { name: "Kitchen", level: "Main", dimensions: "11x10" },
      { name: "Primary Bedroom", level: "Upper", dimensions: "12x11" },
    ],
    photos: [img("photo-1568605114967-8130f3a36994"), img("photo-1570129477492-45c003edd2be")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-06-02",
    modifiedDate: "2026-08-14",
  },
  {
    id: "walkerton-family-1",
    mlsNumber: "SAMPLE-100002",
    isSample: true,
    address: "88 Durham Street E",
    city: "Walkerton",
    province: "ON",
    postalCode: "N0G 2V0",
    latitude: 44.1236,
    longitude: -81.1494,
    price: 599900,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Detached",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2150,
    lotSize: "60 x 130 ft",
    acreage: null,
    garage: "2 Car Attached",
    storeys: 2,
    yearBuilt: 2005,
    waterfront: false,
    headline: "Spacious Family Home Near the Saugeen River",
    description:
      "This well-maintained two-storey home offers room to grow, with an open-concept main floor, a large primary suite, and a private backyard backing onto green space.",
    featureGroups: [
      { title: "Interior", items: ["Open-concept kitchen/great room", "Primary ensuite", "Main floor laundry"] },
      { title: "Exterior", items: ["Deck", "Backs onto green space", "Double garage"] },
    ],
    rooms: [
      { name: "Great Room", level: "Main", dimensions: "18x16" },
      { name: "Primary Bedroom", level: "Upper", dimensions: "15x13" },
    ],
    photos: [img("photo-1600585154340-be6161a56a0c"), img("photo-1600607687939-ce8a6c25118c")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-07-10",
    modifiedDate: "2026-08-20",
  },
  {
    id: "owen-sound-luxury-1",
    mlsNumber: "SAMPLE-100003",
    isSample: true,
    address: "1450 6th Avenue W",
    city: "Owen Sound",
    province: "ON",
    postalCode: "N4K 4L1",
    latitude: 44.5688,
    longitude: -80.9427,
    price: 1249000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Detached",
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3800,
    lotSize: "0.62 acres",
    acreage: 0.62,
    garage: "3 Car Attached",
    storeys: 2,
    yearBuilt: 2018,
    waterfront: false,
    headline: "Executive Home with Escarpment Views",
    description:
      "A striking custom-built home with soaring ceilings, a chef's kitchen, and a walkout lower level. Located minutes from downtown Owen Sound with views over the escarpment.",
    featureGroups: [
      { title: "Interior", items: ["Chef's kitchen with island", "Walkout lower level", "Home office"] },
      { title: "Exterior", items: ["Covered composite deck", "Triple garage", "Professionally landscaped"] },
    ],
    rooms: [
      { name: "Kitchen", level: "Main", dimensions: "20x16" },
      { name: "Primary Suite", level: "Upper", dimensions: "18x15" },
    ],
    photos: [img("photo-1600596542815-ffad4c1539a9"), img("photo-1600047509807-ba8f99d2cdde")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-05-18",
    modifiedDate: "2026-08-01",
  },
  {
    id: "chesley-hobby-farm-1",
    mlsNumber: "SAMPLE-100004",
    isSample: true,
    address: "471 Bruce Road 10",
    city: "Chesley",
    province: "ON",
    postalCode: "N0G 1L0",
    latitude: 44.2919,
    longitude: -81.0942,
    price: 789000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Hobby Farm",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1900,
    lotSize: "9.8 acres",
    acreage: 9.8,
    garage: "Detached Shop",
    storeys: 1.5,
    yearBuilt: 1965,
    waterfront: false,
    headline: "Renovated Farmhouse on Just Under 10 Acres",
    description:
      "A lovingly updated century farmhouse set on rolling acreage with a bank barn, paddocks, and a detached shop. Ideal for hobby farming, horses, or simply enjoying rural space close to Chesley.",
    featureGroups: [
      { title: "Buildings", items: ["Bank barn", "Detached 24x32 shop", "Fenced paddocks"] },
      { title: "Land", items: ["Mix of pasture and bush", "Seasonal creek", "Long private laneway"] },
    ],
    rooms: [
      { name: "Farmhouse Kitchen", level: "Main", dimensions: "16x14" },
      { name: "Primary Bedroom", level: "Upper", dimensions: "13x12" },
    ],
    photos: [img("photo-1500382017468-9049fed747ef"), img("photo-1500076656116-558758c991c1")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-04-22",
    modifiedDate: "2026-07-30",
  },
  {
    id: "rural-bruce-cashcrop-1",
    mlsNumber: "SAMPLE-100005",
    isSample: true,
    address: "215 Concession 4",
    city: "Rural Bruce County",
    province: "ON",
    postalCode: "N0H 1S0",
    latitude: 44.3459,
    longitude: -81.2731,
    price: 2450000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Farm",
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 2400,
    lotSize: "148 acres",
    acreage: 148,
    garage: "Multiple Outbuildings",
    storeys: 2,
    yearBuilt: 1948,
    waterfront: false,
    headline: "148-Acre Cash Crop Farm with Century Home",
    description:
      "A productive cash crop operation with approximately 130 workable acres, systematically tile-drained, plus a solid century farmhouse and multiple outbuildings including a drive shed and grain storage.",
    featureGroups: [
      { title: "Land", items: ["~130 workable acres", "Tile drained", "Balance in bush/pasture"] },
      { title: "Buildings", items: ["Drive shed", "Grain storage", "Machine shop"] },
    ],
    rooms: [{ name: "Farmhouse Kitchen", level: "Main", dimensions: "18x14" }],
    photos: [img("photo-1500595046743-cd271d694d30"), img("photo-1523348837708-15d4a09cfac2")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-03-11",
    modifiedDate: "2026-07-05",
  },
  {
    id: "rural-grey-vacant-land-1",
    mlsNumber: "SAMPLE-100006",
    isSample: true,
    address: "Part Lot 22, Grey Road 3",
    city: "Rural Grey Bruce",
    province: "ON",
    postalCode: "N0H 2C0",
    latitude: 44.4207,
    longitude: -80.9153,
    price: 349000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Vacant Land",
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: null,
    lotSize: "42 acres",
    acreage: 42,
    garage: null,
    storeys: null,
    yearBuilt: null,
    waterfront: false,
    headline: "42 Acres of Vacant Agricultural Land",
    description:
      "Level, workable agricultural land with road frontage and hydro at the lot line. A great opportunity to build your dream home or expand an existing farm operation.",
    featureGroups: [{ title: "Land", items: ["Road frontage", "Hydro at lot line", "Mostly workable"] }],
    rooms: [],
    photos: [img("photo-1500382017468-9049fed747ef")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-06-28",
    modifiedDate: "2026-08-02",
  },
  {
    id: "kincardine-waterfront-1",
    mlsNumber: "SAMPLE-100007",
    isSample: true,
    address: "12 Lakeshore Boulevard",
    city: "Kincardine",
    province: "ON",
    postalCode: "N2Z 1P4",
    latitude: 44.1758,
    longitude: -81.6398,
    price: 1595000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Waterfront",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2600,
    lotSize: "0.4 acres",
    acreage: 0.4,
    garage: "2 Car Attached",
    storeys: 2,
    yearBuilt: 2012,
    waterfront: true,
    headline: "Lake Huron Waterfront with Private Sand Beach",
    description:
      "Wake up to sunsets over Lake Huron in this beautifully finished waterfront home with a private beach, expansive deck, and walls of windows framing the water.",
    featureGroups: [
      { title: "Waterfront", items: ["Private sand beach", "Unobstructed sunset views", "Steps to the water"] },
      { title: "Interior", items: ["Floor-to-ceiling windows", "Open-concept living", "Walkout lower level"] },
    ],
    rooms: [{ name: "Living Room", level: "Main", dimensions: "22x18" }],
    photos: [img("photo-1499793983690-e29da59ef1c2"), img("photo-1505142468610-359e7d316be0")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-05-02",
    modifiedDate: "2026-08-10",
  },
  {
    id: "port-elgin-cottage-1",
    mlsNumber: "SAMPLE-100008",
    isSample: true,
    address: "77 Lakeshore Road",
    city: "Port Elgin",
    province: "ON",
    postalCode: "N0H 2C5",
    latitude: 44.4361,
    longitude: -81.3925,
    price: 899000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Cottage",
    bedrooms: 3,
    bathrooms: 1,
    squareFeet: 1100,
    lotSize: "0.25 acres",
    acreage: 0.25,
    garage: null,
    storeys: 1,
    yearBuilt: 1985,
    waterfront: true,
    headline: "Classic Lake Huron Cottage Steps from the Beach",
    description:
      "A well-loved three-season cottage just a short walk to Port Elgin's beautiful sandy beach. Simple, comfortable, and full of potential — perfect as a getaway or a rebuild opportunity.",
    featureGroups: [{ title: "Location", items: ["Short walk to beach", "Quiet dead-end road"] }],
    rooms: [{ name: "Main Living Area", level: "Main", dimensions: "20x14" }],
    photos: [img("photo-1505691938895-1758d7feb511"), img("photo-1449158743715-0a90ebb6d2d8")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-06-15",
    modifiedDate: "2026-08-11",
  },
  {
    id: "southampton-condo-1",
    mlsNumber: "SAMPLE-100009",
    isSample: true,
    address: "205 High Street, Unit 12",
    city: "Southampton",
    province: "ON",
    postalCode: "N0H 2L0",
    latitude: 44.4881,
    longitude: -81.3736,
    price: 459000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Condo",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1050,
    lotSize: null,
    acreage: null,
    garage: "1 Underground Space",
    storeys: 1,
    yearBuilt: 2016,
    waterfront: false,
    headline: "Low-Maintenance Condo Minutes from the Beach",
    description:
      "A bright, low-maintenance condo in a well-run building close to downtown Southampton and the beach. Perfect for downsizers or as a lock-and-leave second home.",
    featureGroups: [{ title: "Building", items: ["Elevator building", "Underground parking", "Visitor parking"] }],
    rooms: [{ name: "Living/Dining", level: "Main", dimensions: "16x14" }],
    photos: [img("photo-1502672260266-1c1ef2d93688"), img("photo-1512917774080-9991f1c4c750")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-07-01",
    modifiedDate: "2026-08-16",
  },
  {
    id: "sauble-beach-waterfront-land-1",
    mlsNumber: "SAMPLE-100010",
    isSample: true,
    address: "Lot 14, 4th Avenue N",
    city: "Sauble Beach",
    province: "ON",
    postalCode: "N0H 2G0",
    latitude: 44.6317,
    longitude: -81.2467,
    price: 525000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Vacant Land",
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: null,
    lotSize: "66 x 150 ft",
    acreage: null,
    garage: null,
    storeys: null,
    yearBuilt: null,
    waterfront: true,
    headline: "Vacant Waterfront Building Lot Near Sauble Beach",
    description:
      "A rare vacant lot close to one of Ontario's most popular beaches. Bring your builder and design the cottage or home you've always wanted, just minutes to shops and the water.",
    featureGroups: [{ title: "Land", items: ["Close to Sauble Beach", "Services at lot line"] }],
    rooms: [],
    photos: [img("photo-1519046904884-53103b34b206")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-06-05",
    modifiedDate: "2026-07-28",
  },
  {
    id: "hanover-investment-1",
    mlsNumber: "SAMPLE-100011",
    isSample: true,
    address: "36 King Street E",
    city: "Hanover",
    province: "ON",
    postalCode: "N4N 2R2",
    latitude: 44.1518,
    longitude: -81.0329,
    price: 649000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Investment",
    bedrooms: 6,
    bathrooms: 3,
    squareFeet: 2800,
    lotSize: "40 x 120 ft",
    acreage: null,
    garage: null,
    storeys: 2,
    yearBuilt: 1962,
    waterfront: false,
    headline: "Legal Triplex in Downtown Hanover",
    description:
      "A well-maintained legal triplex with three self-contained units, each with separate hydro meters. Strong rental demand in this location, walking distance to downtown amenities.",
    featureGroups: [{ title: "Income", items: ["3 self-contained units", "Separate hydro meters", "Coin laundry"] }],
    rooms: [],
    photos: [img("photo-1560518883-ce09059eeffa"), img("photo-1580587771525-78b9dba3b914")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-04-30",
    modifiedDate: "2026-07-19",
  },
  {
    id: "walkerton-dairy-farm-1",
    mlsNumber: "SAMPLE-100012",
    isSample: true,
    address: "780 Concession 2 N",
    city: "Rural Bruce County",
    province: "ON",
    postalCode: "N0G 2V0",
    latitude: 44.1602,
    longitude: -81.1987,
    price: 3295000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Farm",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2700,
    lotSize: "210 acres",
    acreage: 210,
    garage: "Freestall Barn + Parlour",
    storeys: 2,
    yearBuilt: 1995,
    waterfront: false,
    headline: "210-Acre Dairy Farm with Modern Freestall Barn",
    description:
      "A well-run dairy operation featuring a modern freestall barn, double-8 milking parlour, and approximately 180 workable acres. Updated 4-bedroom farmhouse included. Quota not included — to be discussed with Brent.",
    featureGroups: [
      { title: "Buildings", items: ["Freestall barn", "Double-8 parlour", "Commodity shed"] },
      { title: "Land", items: ["~180 workable acres", "Balance in pasture/bush"] },
    ],
    rooms: [{ name: "Farmhouse Kitchen", level: "Main", dimensions: "20x16" }],
    photos: [img("photo-1500595046743-cd271d694d30"), img("photo-1516467508483-a7212febe31a")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-02-14",
    modifiedDate: "2026-06-30",
  },
  {
    id: "owen-sound-townhouse-1",
    mlsNumber: "SAMPLE-100013",
    isSample: true,
    address: "540 9th Avenue E, Unit 4",
    city: "Owen Sound",
    province: "ON",
    postalCode: "N4K 2Y3",
    latitude: 44.5657,
    longitude: -80.9366,
    price: 389900,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Townhouse",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1400,
    lotSize: null,
    acreage: null,
    garage: "1 Car Attached",
    storeys: 2,
    yearBuilt: 2009,
    waterfront: false,
    headline: "Affordable End-Unit Townhouse",
    description:
      "A bright end-unit townhouse with low condo fees, an attached garage, and a fenced yard. Great value for first-time buyers or investors in Owen Sound.",
    featureGroups: [{ title: "Interior", items: ["End unit", "Finished basement", "Attached garage"] }],
    rooms: [{ name: "Living Room", level: "Main", dimensions: "15x12" }],
    photos: [img("photo-1580587771525-78b9dba3b914")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-07-20",
    modifiedDate: "2026-08-22",
  },
  {
    id: "kincardine-mixed-farm-1",
    mlsNumber: "SAMPLE-100014",
    isSample: true,
    address: "112 Concession 6",
    city: "Kincardine",
    province: "ON",
    postalCode: "N2Z 2X6",
    latitude: 44.2103,
    longitude: -81.5231,
    price: 1875000,
    status: "Coming Soon",
    listingType: "For Sale",
    propertyType: "Farm",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    lotSize: "95 acres",
    acreage: 95,
    garage: "Bank Barn + Drive Shed",
    storeys: 1.5,
    yearBuilt: 1972,
    waterfront: false,
    headline: "95-Acre Mixed Farm — Coming Soon",
    description:
      "A versatile mixed farm with a blend of workable land, pasture, and bush, plus a bank barn suited to beef or mixed livestock. Full details available soon — contact Brent to be notified first.",
    featureGroups: [{ title: "Land", items: ["Mixed workable/pasture/bush", "Bank barn", "Drive shed"] }],
    rooms: [],
    photos: [img("photo-1500382017468-9049fed747ef")],
    listingBrokerage: "eXp Realty",
    listingAgent: "Brent Koelen",
    listingDate: "2026-08-25",
    modifiedDate: "2026-08-25",
  },
];
